### ISSUE TITLE
[Clean] Implementing DID's and VC's into an Open Source Invoice Management Application

### ISSUE THREAD

**Issue by wsdOgawa** [eea-oasis/baseline-grants#87]
## Details on Grant Work

The details of the grant work are for implementing DID's, VC's into [Private Invoice.](https://github.com/WebServiceDevelopment/PrivateInvoice). Private Invoice is an Open Source project under the Apache 2.0 license. The purpose of Private Invoice is to provide a self-hosted server where individuals can create invoices and send or receive from a whitelisted list of contacts. Invoice can be paid with Ethereum in the application. And the state of the invoice ('sent', 'confirmed', 'paid'), is kept consistent between each of nodes.

The scope of this proposal is to:
- Implement Invoices as Verifiable Credentials
- Implement DID's for organization members to sign credentials
- Implement sending invoices as presentations to other Private Invoice instances
- Use Credentials to manage contacts

Note that `Private Invoice` is the name of the application in our repository for reference. As the application is available under Apache 2.0 we have no issues with submitting a fork with other branding or name if required.

## Motivation and Overview

At Web Service Development, we've have almost a decade of experience working with business applications. We believe that in order to demonstrate traceability※ with financial records, the following three conditions are required:

1. Records of the invoices are kept (using Verifiable Credentials insures integrity)
2. Decentralized Identifier to show that a key is resolvable to an entity
3. Blockchain record of the transaction to show the agreed-upon price was paid for the invoice

One pain point that we've experienced is trying to work with legacy banking institutions, which often require having a contact at that institution in order to get a contract to use their services. We believe that blockchain represents the future of business as it defines a specific implementation, where anyone who is able to interact with the technology to make transactions. 

We also think that decentralization and creating multiple nodes for an application reduces the number of eggs in one basket and avoids having a central server with all customer data in a single location, which can either be exploited or attacked. And we believe that companies should be in control of their own data, which means hosting their own node, having access to their own keys and being in control of their own data.

※日本語では「証憑性」という造語を作成した。  
証憑が真正であることを示すための条件を「証憑性」と定義する。  

## Value to the Baseline Protocol

We think that having an invoice application where the state of the invoice is managed between multiple parties is a simple application that shows the capabilities of the Baseline protocol. The ability to make payments on invoices with Ethereum is another step to encourage business adoption of blockchain technologies.

### Risks

In order to mitigate this risk we've done several tech-spikes to insure that we have an understanding of how all of the pieces work. And we've implemented the application in a format that doesn't rely on DID's or VC's to work as a web application, to allow us to swap out parts and still insure that the application instead of taking an all-or-nothing approach of building in new concepts from the ground up. 

### Limitations

One limitation that we're using Ganache for both payment and the did method. We have tech spikes for implementing the application with a testnet such as Ropsten or Rinkeby, but to make it easy to test and evaluate we're targeting Ganache. 

Another limitation is that we're only allowing one mnemonic phrase per organization in the application and one did per member. Further versions of the application could have more fine grained version of key management, but for a core implementation we want to keep things simple.

BRI, ERC20, NFT's and multiple blockchains, are not implemented in the scope of this proposal. Only payments made with Ethereum using ganache. 

## Deliverables / Schedule / Milestones

We've outline a [milestone with an internal due by date of September 30th 2022](https://github.com/WebServiceDevelopment/PrivateInvoice/milestone/1) for the features we intend to implement in this proposal. The milestone contains five issues which represent the deliverables outlined in this proposal.

- [x] [Update Contacts to use Verifiable Business Cards](https://github.com/WebServiceDevelopment/PrivateInvoice/issues/3)
- [x] [Split Users into Members and Organizations](https://github.com/WebServiceDevelopment/PrivateInvoice/issues/2)
- [x] [Implement with Invoices as Verifiable Credentials](https://github.com/WebServiceDevelopment/PrivateInvoice/issues/5)
- [x] [Update Invoice with Presentation Status Messages](https://github.com/WebServiceDevelopment/PrivateInvoice/issues/6)
- [x] [Make Payments with Ethereum and store records in IPFS](https://github.com/WebServiceDevelopment/PrivateInvoice/issues/7)

Our plan is to finish implementation on these features before the end of August to provide time for testing and documentation in able to have a stable core release by September 30th. This time has been decided since we want to look for funding by the end of the year. 

## Budget and Justification

The budget being asked for this in this proposal is $5,000. The work on DID's, VC's and Ethereum is work that we intend on working on anyways, and would like some amount of funding to be able to continue to work on completely Open Source implementations of these technologies. 

## Applicant Background

Kousei Ogawa (self) has thirty years of working in the IT industry in Japan working for a large corporation before creating his own company. He has extensive knowledge with working with CentOS and open source technologies. And has been managing the server-side Javascript Application server [Jaxer](https://github.com/WebServiceDevelopment/Jaxer) for business use in Japan under the GPL license.

### Community Grant Agreement 
I understand and agree to the ['Process for Approved Grants' outlined here](https://github.com/eea-oasis/baseline-grants/blob/main/README.md)
- [x] I agree 

--- 

Posting a clean version of this on a issue page, with a few edits to parts that will not be implemented in the current iteration. 

I think right now this doesn't fit cleanly into the categories of either a BLIP or an RFP as such I dropped the budget to reflect this. The goal for this project is to implement the state management for invoices in the way described in this video: https://www.youtube.com/watch?v=cDMtthZtDM8

![Baseline Protocol - The (BASE)ics - Baseline Architecture Simplified for Everyone ft. Keith Salzman](https://user-images.githubusercontent.com/5275924/187059790-6d255d9e-07ad-4172-be06-9906939b1cae.png)

My first goal for this year is to have core functionality working with `did:key`, credentials, presentations, and some form of state management between two parties, which I think I have. Right now my goals for this project are to port the backend to Typescript, document and simplify the server-side modules, and set up CI/CD.

**Comment by Therecanbeonlyone1969** [comment]
@wsdOgawa I like the proposal a lot. Unfortunately, the zkp part of the BPI is missing, see the standard doc [link](https://github.com/eea-oasis/baseline-standard/blob/main/core/baseline-core-v1.0-psd01.md#r225), at least as far as I can see. It would be nice if you could stick to the standard in this aspect, including the [API standard](https://github.com/eea-oasis/baseline-standard/blob/main/api/baseline-api-v1.0.0.yaml), if at all possible. Thank you! cc @GoldenBit0

**Comment by mehranshakeri** [comment]
@wsdOgawa This is a good demonstration of connecting different components to facilitate a business process. My question would be "what is the reason to use IPFS and what data is stored there?" e.g., I don't think any business exposes their invoices publicly, so I wouldn't store invoice in IPFS.

**Comment by wsdOgawa** [comment]
> "what is the reason to use IPFS and what data is stored there?" e.g., I don't think any business exposes their invoices publicly, so I wouldn't store invoice in IPFS.

This was discussed previously here: https://github.com/eea-oasis/baseline-grants/issues/76#issuecomment-1200323315
>For the use of IPFS we wanted to have some kind of third party storage outside of the Private Invoice node with the understanding that anything written to the blockchain would be public knowledge. The current implementation is a first-pass quick and dirty solution. I'll look into the options you listed to see if this can be improved on to allow for privacy between the parties involved for implementation in a later version.

> I like the proposal a lot. Unfortunately, the zkp part of the BPI is missing, see the standard doc [link](https://github.com/eea-oasis/baseline-standard/blob/main/core/baseline-core-v1.0-psd01.md#r225), at least as far as I can see. It would be nice if you could stick to the standard in this aspect, including the [API standard](https://github.com/eea-oasis/baseline-standard/blob/main/api/baseline-api-v1.0.0.yaml), if at all possible.

Thanks for the recommendation, but this is not feasible for a side project I'm working on the corner of my desk to be done by the end of the year. As stated above:

> My first goal for this year is to have core functionality working with did:key, credentials, presentations, and some form of state management between two parties, which I think I have. Right now my goals for this project are to port the backend to Typescript, document and simplify the server-side modules, and set up CI/CD.

**Comment by Therecanbeonlyone1969** [comment]
@wsdOgawa the zkp part is required. However, if you need more time, we can extend the timeframe for the zkp part beyond the end of this year. Let us know your thoughts.

**Comment by wsdOgawa** [comment]
> @wsdOgawa the zkp part is required. However, if you need more time, we can extend the timeframe for the zkp part beyond the end of this year. Let us know your thoughts.

That would be helpful. I want to consolidate what I have and do tech spikes about that parts that I'm not familiar with before trying to fit it into a working project. 

From the end of this year I have other projects that are going to need my attention, so it's going to be hard to give you a new timeline for updates that needs to be done on this.

**Comment by Therecanbeonlyone1969** [comment]
@wsdOgawa could you give us a rough sense on when you would be done

**Comment by wsdOgawa** [comment]
> could you give us a rough sense on when you would be done

Currently I'm working on completing my goals (port the backend to Typescript, document and simplify the server-side modules, and set up CI/CD) by the end of the year. I've had a lot of other work to follow up on, which has made it difficult to commit to a hard schedule for open source.

**Comment by GoldenBit0** [comment]
@wsdOgawa I'm going to close this issues due to going stale. 

Please reach out when you'd like to continue discussing this work by emailing baseline-team@oasis-open.org or via Slack! https://join.slack.com/t/ethereum-baseline/shared_invite/zt-1gu6trxeq-~GO7xe9Z2doeynrUEzaPuw
